services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      ["/bin/sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT} --loop uvloop --http httptools --workers 1" ]
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    restart: on-failure
    mem_limit: 512m
    cpus: 0.5
